### ISSUE TITLE
Can‘t find the CameraID in the latest version

### ISSUE THREAD

**Issue by YinXiuYu** [lessthanoptimal/BoofAndroidDemo#23]
@lessthanoptimal  
Can‘t find the CameraID in the latest version, please confirm and check.

**Comment by lessthanoptimal** [comment]
It's referencing a developmental version of BoofCV and get out of sync. I've fixed that and made sure Maven Central has the latest code. Pull and It should build now. Might need to refresh your jar cache.

**Comment by YinXiuYu** [comment]
@lessthanoptimal Thanks for the quick feedback！

**Comment by YinXiuYu** [comment]
@lessthanoptimal Thanks for the quick feedback,but still not working,

**Comment by lessthanoptimal** [comment]
Can you paste the full error message?

**Comment by YinXiuYu** [comment]
It is caused by cache problems, and it has been able to work normally, thanks a lot!
